---
title: "cori-theme-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{cori-theme-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```
abhishek's workspace

```{r example2}
library(ggplot2)
library(tidyverse)
library(coriplot)
library(ggplot2)
library(tidyverse)

theme_set(theme_cori())
data("remote_work_by_ed_level")
fig <- remote_work_by_ed_level %>%
  ggplot(aes(as.Date(date), pct_working_remotely, group = education_level, color = education_level)) +
  geom_line(lwd = 1.5) +
  xlab("") +
  scale_x_date(date_breaks = "1 month", date_labels =  "%b") + 
  scale_y_continuous(expand = c(0, 0)) +
  geom_point(size = 2)+
  ggtitle("Line Chart - straight lines") +
  labs(subtitle = "Multiple Colors")+
  scale_color_cori() 
fig 
```

```{r example3}
data("time_series_sample_data")
twoColDf<-time_series_sample_data[,c("date","less_than_high_school","high_school_no_college")]
colnames(twoColDf)<-c("date","urban","rural")
df2col<- tidyr::pivot_longer(
  twoColDf,
  cols = !date,
  names_to = "education_level",
  values_to = "pct_working_remotely"
)

fig <- df2col %>%
  ggplot(aes(as.Date(date), pct_working_remotely, group = education_level, color = education_level)) +
  geom_line(lwd = 1.5) +
  xlab("") +
  scale_x_date(date_breaks = "1 month", date_labels =  "%b") + 
  scale_y_continuous(expand = c(0, 0)) +
  geom_point(size = 2)+
  ggtitle("Line Chart - straight lines") +
  labs(subtitle = "Only 2 Columns")+
  ylab("Percentage Working Remotely")+
  scale_color_cori(cori_primary) 
fig 
```


This is a basic example which shows you how to make curved lines:

```{r example4}
fig <- remote_work_by_ed_level[1:20,] %>%
  ggplot(aes(as.Date(date),
             pct_working_remotely,
             group = education_level,
             color = education_level)) +
  geom_smooth(method = 'loess',
              linetype = 1,
              size = 1,
              lwd = 1.5,
              se= FALSE) +
  xlab("") +
  scale_x_date(date_breaks = "1 month", date_labels =  "%b") + 
  scale_y_continuous(expand = c(0, 0)) +
  geom_point(size = 2)+
  ggtitle("Line Chart - Curved lines")+
  labs(subtitle = "Multiple Colors")+
  scale_color_cori(cori_primary) 
flush_ticks(fig) 
```


```{r}

ggplot2::update_geom_defaults("line", list(color = "#00835D", size = 1))
ggplot2::update_geom_defaults("vline", list(color = "#D2D6D7", size = 0.264))
ggplot2::update_geom_defaults("hline", list(color = "#D2D6D7", size = 0.264))

d <- data.frame(a=c(1,2,3,4,1,2,3,4),b=c(1,1,1,1,2,2,2,2),c=c(4,6,5,7,8,3,5,6))
d$b<-as.factor(d$b)

# ggplot(data=d,aes(x=a, y=c, group=b, color=b))+
#   geom_vline(xintercept = mean(d$a))+
#   geom_text(aes(x=mean(a), label="\nthreshold", y=20), color="#26535C", text=element_text(size=11))+
#   geom_line()+
#   theme_cori()+
#   scale_color_cori()

shift<-0
f<-ggplot(data=d,aes(x=a, y=c, group=b, color=b))+
  geom_line()+
  theme_cori()+
  scale_color_cori()+
  #annotate(geom = 'text',x=4.5+shift,y=Inf, label="label", color="#26535C", vjust="top")+
  #threshold(axis="y",6, label="\nthreshold")+
  
threshold(f,axis="y",5, label="\nthreshold",shift=0.4)




```
